### ISSUE TITLE
Cannot import Markup from flask

### ISSUE THREAD

**Issue by unsliced** [singingwolfboy/flask-misaka#30]
With flask 3.0.0, flask-misaka-1.0.0 is broken: 

```python
from flask import Flask
from flask_misaka import Misaka

app = Flask(__name__)
Misaka(app)
```

```
(.venv) $ flask --app dashboard run
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'dashboard', an ImportError was raised:

Traceback (most recent call last):
  File ".../.venv/lib/python3.10/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File ".../dashboard.py", line 1, in <module>
    from app import app
  File ".../app/__init__.py", line 2, in <module>
    from flask_misaka import Misaka
  File ".../.venv/lib/python3.10/site-packages/flask_misaka.py", line 6, in <module>
    from flask import Markup
ImportError: cannot import name 'Markup' from 'flask' (.../.venv/lib/python3.10/site-packages/flask/__init__.py)
```

The flask devs seem to suggest that this is [not their problem](https://github.com/pallets/flask/issues/5353).

**Comment by singingwolfboy** [comment]
This should now be fixed in [Flask-Misaka 1.0.1](https://pypi.org/project/Flask-Misaka/1.0.1/).
